#include "stdafx.h"
#include "OpenTypeLangTags.h"

//this array contains lang tags and descriptions from https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags,
//along with 3 char codes from hb-ot-tag-table.hh (matched to the previous by opentype lang tag)
//libass currently supports only two-letter codes, but harfbuzz supports more.
//libass will not find the language if it does not match the hbtag below, so only the 2-char codes work

OpenTypeLang::OpenTypeLangTag OpenTypeLang::OpenTypeLangTags[603] =
{
    { L"Aari", "ARI ", "aiw"},
    { L"Abaza", "ABA ", "abq"},
    { L"Abkhazian", "ABK ", "ab"},
    { L"Achi", "ACR ", "acr"},
    { L"Acholi", "ACH ", "ach"},
    { L"Adyghe ", "ADY ", "ady"},
    { L"Afar", "AFR ", "aa"},
    { L"Afrikaans", "AFK ", "af"},
    { L"Agaw", "AGW ", "ahg"},
    { L"Aiton", "AIO ", "aio"},
    { L"Akan", "AKA ", "ak"},
    { L"Albanian", "SQI ", "aae"},
    { L"Alsatian", "ALS ", "gsw"},
    { L"Altai", "ALT ", "alt"},
    { L"Amharic", "AMH ", "am"},
    { L"Anglo-Saxon", "ANG ", "ang"},
    { L"Arabic", "ARA ", "aao"},
    { L"Aragonese", "ARG ", "an"},
    { L"Arakwa", "RKW ", "rkw"},
    { L"Armenian East", "HYE0", "hy"},
    { L"Armenian", "HYE ", "hy"},
    { L"Aromanian", "RUP ", "rup"},
    { L"Arpitan", "FRP ", "frp"},
    { L"Assamese", "ASM ", "as"},
    { L"Asturian", "AST ", "ast"},
    { L"Athapaskan", "ATH ", "aht"},
    { L"Avar", "AVR ", "av"},
    { L"Awadhi", "AWA ", "awa"},
    { L"Aymara", "AYM ", "ay"},
    { L"Azerbaijani", "AZE ", "az"},
    { L"Badaga", "BAD ", "bfq"},
    { L"Baghelkhandi", "BAG ", "bfy"},
    { L"Bagri", "BGQ ", "bgq"},
    { L"Balante", "BLN ", "bjt"},
    { L"Balinese", "BAN ", "ban"},
    { L"Balkar", "BAL ", "krc"},
    { L"Balti", "BLT ", "bft"},
    { L"Baluchi", "BLI ", "bal"},
    { L"Bambara (Bamanankan)", "BMB ", "bm"},
    { L"Bamileke", "BML ", "bai"},
    { L"Banda", "BAD0", "bad"},
    { L"Bandjalang", "BDY ", "bdy"},
    { L"Bashkir", "BSH ", "ba"},
    { L"Basque", "EUQ ", "eu"},
    { L"Batak Simalungun", "BTS ", "bts"},
    { L"Batak Toba", "BBC ", "bbc"},
    { L"Baulé", "BAU ", "bci"},
    { L"Bavarian", "BAR ", "bar"},
    { L"Belarussian", "BEL ", "be"},
    { L"Bemba", "BEM ", "bem"},
    { L"Bench", "BCH ", "bcq"},
    { L"Bengali", "BEN ", "bn"},
    { L"Berber", "BBR ", "ber"},
    { L"Beti", "BTI ", "beb"},
    { L"Bhili", "BHI ", "bhb"},
    { L"Bhojpuri", "BHO ", "bho"},
    { L"Bible Cree", "BCR ", ""},
    { L"Biko", "BIK ", "bcl"},
    { L"Bilen", "BIL ", "byn"},
    { L"Bishnupriya Manipuri", "BPY ", "bpy"},
    { L"Bislama", "BIS ", "bi"},
    { L"Blackfoot", "BKF ", "bla"},
    { L"Bodo", "BRX ", "brx"},
    { L"Bosnian", "BOS ", "bs"},
    { L"Bouyei", "PCC ", "pcc"},
    { L"Brahui", "BRH ", "brh"},
    { L"Braj Bhasha", "BRI ", "bra"},
    { L"Breton", "BRE ", "br"},
    { L"Bugis", "BUG ", "bug"},
    { L"Bulgarian", "BGR ", "bg"},
    { L"Bumthangkha", "KJZ ", "kjz"},
    { L"Burmese", "BRM ", "my"},
    { L"Burushaski", "BSK ", "bsk"},
    { L"Cajun French", "FRC ", "frc"},
    { L"Carrier", "CRR ", "caf"},
    { L"Catalan", "CAT ", "ca"},
    { L"Cebuano", "CEB ", "ceb"},
    { L"Central Yupik", "ESU ", "esu"},
    { L"Chaha Gurage", "CHG ", "sgw"},
    { L"Chamorro", "CHA ", "ch"},
    { L"Chattisgarhi", "CHH ", "hne"},
    { L"Chechen", "CHE ", "ce"},
    { L"Cherokee", "CHR ", "chr"},
    { L"Cheyenne", "CHY ", "chy"},
    { L"Chichewa (Chewa, Nyanja)", "CHI ", ""},
    { L"Chiga", "CGG ", "cgg"},
    { L"Chin", "QIN ", "bgr"},
    { L"Chinantec", "CCHN", "cco"},
    { L"Chinese Phonetic", "ZHP ", ""},
    { L"Chinese Simplified", "ZHS ", "cdo"},
    { L"Chinese Traditiona", "ZHT ", "lzh"},
    { L"Chinese, Hong Kong SAR", "ZHH ", ""},
    { L"Chipewyan", "CHP ", "chp"},
    { L"Chittagonian", "CTG ", "ctg"},
    { L"Choctaw", "CHO ", "cho"},
    { L"Chukchi", "CHK ", "ckt"},
    { L"Church Slavonic", "CSL ", "cu"},
    { L"Chuukese", "CHK0", "chk"},
    { L"Chuvash", "CHU ", "cv"},
    { L"Comorian", "CMR ", "swb"},
    { L"Coptic", "COP ", "cop"},
    { L"Cornish", "COR ", "kw"},
    { L"Corsican", "COS ", "co"},
    { L"Cree", "CRE ", "cr"},
    { L"Creoles", "CPP ", "cpe"},
    { L"Crimean Tatar", "CRT ", "crh"},
    { L"Croatian", "HRV ", "hr"},
    { L"Czech", "CSY ", "cs"},
    { L"Dan", "DNJ ", "dnj"},
    { L"Dangme", "DNG ", "ada"},
    { L"Danish", "DAN ", "da"},
    { L"Dargwa", "DAR ", "dar"},
    { L"Dari", "DRI ", "drw"},
    { L"Dayi", "DAX ", "dax"},
    { L"Dehong Dai", "TDD ", "tdd"},
    { L"Dhangu", "DHG ", "dhg"},
    { L"Dhuwa", "DUJ ", "duj"},
    { L"Dimli", "DIQ ", "diq"},
    { L"Dinka", "DNK ", "dib"},
    { L"Divehi (Dhivehi, Maldivian)", "DHV ", ""},
    { L"Divehi (Dhivehi, Maldivian)", "DIV ", ""},
    { L"Djambarrpuyngu", "DJR0", "djr"},
    { L"Dogri", "DGO ", "dgo"},
    { L"Dogri", "DGR ", "doi"},
    { L"Dungan", "DUN ", "dng"},
    { L"Dutch (Flemish)", "FLE ", "vls"},
    { L"Dutch", "NLD ", "nl"},
    { L"Dzongkha", "DZN ", "adp"},
    { L"Eastern Cham", "CJM ", "cjm"},
    { L"Eastern Cree", "ECR ", "crj"},
    { L"Eastern Maninkakan", "EMK ", "emk"},
    { L"Eastern Pwo Karen", "KJP ", "kjp"},
    { L"Ebira", "EBI ", "igb"},
    { L"Edo", "EDO ", "bin"},
    { L"Efik", "EFI ", "efi"},
    { L"English", "ENG ", "en"},
    { L"Erzya", "ERZ ", "myv"},
    { L"Esperanto", "NTO ", "eo"},
    { L"Estonian", "ETI ", "ekk"},
    { L"Even", "EVN ", "eve"},
    { L"Evenki", "EVK ", "evn"},
    { L"Ewe", "EWE ", "ee"},
    { L"Fang", "FAN0", "fan"},
    { L"Fanti", "FAT ", "fat"},
    { L"Faroese", "FOS ", "fo"},
    { L"Fe’fe’", "FMP ", "fmp"},
    { L"Fijian", "FJI ", "fj"},
    { L"Filipino", "PIL ", "fil"},
    { L"Finnish", "FIN ", "fi"},
    { L"Fon", "FON ", "fon"},
    { L"Forest Nenets", "FNE ", "enf"},
    { L"French Antillean", "FAN ", "acf"},
    { L"French", "FRA ", "fr"},
    { L"Frisian", "FRI ", "fy"},
    { L"Friulian", "FRL ", "fur"},
    { L"Fulah", "FUL ", "ff"},
    { L"Futa", "FTA ", "fuf"},
    { L"Ga", "GAD ", "gaa"},
    { L"Gagauz", "GAG ", "gag"},
    { L"Galician", "GAL ", "gl"},
    { L"Ganda", "LUG ", "lg"},
    { L"Garhwali", "GAW ", "gbm"},
    { L"Garo", "GRO ", "grt"},
    { L"Garshuni", "GAR ", ""},
    { L"Geez", "GEZ ", "gez"},
    { L"Georgian", "KAT ", "ka"},
    { L"German", "DEU ", "de"},
    { L"Gilaki", "GLK ", "glk"},
    { L"Gilyak", "GIL ", "niv"},
    { L"Githabu", "GIH ", "gih"},
    { L"Gogo", "GOG ", "gog"},
    { L"Gondi", "GON ", "esg"},
    { L"Greek", "ELL ", "el"},
    { L"Greenlandic", "GRN ", "kl"},
    { L"Guarani", "GUA ", "gn"},
    { L"Gujarati", "GUJ ", "gu"},
    { L"Gumatj", "GNN ", "gnn"},
    { L"Gumuz", "GMZ ", "guk"},
    { L"Gupapuyngu", "GUF ", "guf"},
    { L"Gusii", "GUZ ", "guz"},
    { L"Haitian (Haitian Creole)", "HAI ", "ht"},
    { L"Halam (Falam Chin)", "HAL ", "cfm"},
    { L"Hammer-Banna", "HBN ", "amf"},
    { L"Harari", "HRI ", "har"},
    { L"Harauti", "HAR ", "hoj"},
    { L"Haryanvi", "BGC ", "bgc"},
    { L"Hausa", "HAU ", "ha"},
    { L"Hawaiian", "HAW ", "haw"},
    { L"Haya", "HAY ", "hay"},
    { L"Hazaragi", "HAZ ", "haz"},
    { L"Hebrew", "IWR ", "he"},
    { L"Herero", "HER ", "hz"},
    { L"High Mari", "HMA ", "mrj"},
    { L"Hiligaynon", "HIL ", "hil"},
    { L"Hindi", "HIN ", "hi"},
    { L"Hindko", "HND ", "hnd"},
    { L"Hiri Motu", "HMO ", "ho"},
    { L"Hmong Daw", "MWW ", "mww"},
    { L"Hmong", "HMN ", "cqd"},
    { L"Ho", "HO ", ""},
    { L"Hungarian", "HUN ", "hu"},
    { L"Iban", "IBA ", "iba"},
    { L"Ibibio", "IBB ", "ibb"},
    { L"Icelandic", "ISL ", "is"},
    { L"Ido", "IDO ", "io"},
    { L"Igbo", "IBO ", "ig"},
    { L"Ijo languages", "IJO ", "ijc"},
    { L"Ilokano", "ILO ", "ilo"},
    { L"Inari Sami", "ISM ", "smn"},
    { L"Indonesian", "IND ", "id"},
    { L"Ingush", "ING ", "inh"},
    { L"Interlingua", "INA ", "ia"},
    { L"Interlingue", "ILE ", "ie"},
    { L"Inuktitut", "INU ", "ike"},
    { L"Inupiat", "IPK ", "esi"},
    { L"Irish Traditiona", "IRT ", ""},
    { L"Irish", "IRI ", "ga"},
    { L"Italian", "ITA ", "it"},
    { L"Jamaican Creole", "JAM ", "jam"},
    { L"Japanese", "JAN ", "ja"},
    { L"Javanese", "JAV ", "jv"},
    { L"Jula", "JUL ", "dyu"},
    { L"Kabardian", "KAB ", "kbd"},
    { L"Kabuverdianu (Crioulo)", "KEA ", "kea"},
    { L"Kabyle", "KAB0", "kab"},
    { L"Kachchi", "KAC ", "kfr"},
    { L"Kalenjin", "KAL ", "enb"},
    { L"Kalmyk", "KLM ", "xal"},
    { L"Kamba", "KMB ", "kam"},
    { L"Kanauji", "BJJ ", "bjj"},
    { L"Kannada", "KAN ", "kn"},
    { L"Kanuri", "KNR ", "kby"},
    { L"Kaqchike", "CAK ", "cak"},
    { L"Karachay", "KAR ", "krc"},
    { L"Karaim", "KRM ", "kdr"},
    { L"Karakalpak", "KRK ", "kaa"},
    { L"Karelian", "KRL ", "krl"},
    { L"Karen", "KRN ", "kar"},
    { L"Kashmiri", "KSH ", "ks"},
    { L"Kashubian", "CSB ", "csb"},
    { L"Kazakh", "KAZ ", "kk"},
    { L"Kebena", "KEB ", "ktb"},
    { L"Kekchi", "KEK ", "kek"},
    { L"Khakass", "KHA ", "kjh"},
    { L"Khamti Shan", "KHT ", "kht"},
    { L"Khanty-Kazim", "KHK ", "kca"},
    { L"Khanty-Shurishkar", "KHS ", "kca"},
    { L"Khanty-Vakhi", "KHV ", "kca"},
    { L"Khasi", "KSI ", "kha"},
    { L"Khengkha", "XKF ", "xkf"},
    { L"Khmer", "KHM ", "km"},
    { L"Khorasani Turkic", "KMZ ", "kmz"},
    { L"Khowar", "KHW ", "khw"},
    { L"Khutsuri Georgian", "KGE ", ""},
    { L"Kikongo", "KON ", "ktu"},
    { L"Kikuyu (Gikuyu)", "KIK ", "ki"},
    { L"Kildin Sami", "KSM ", "sjd"},
    { L"Kinyarwanda", "RUA ", "rw"},
    { L"Kirghiz (Kyrgyz)", "KIR ", "ky"},
    { L"Kiribati (Gilbertese)", "GIL0", "gil"},
    { L"Kirmanjki", "KIU ", "kiu"},
    { L"Kisii", "KIS ", "kqs"},
    { L"Kituba", "MKW ", "mkw"},
    { L"Kodagu", "KOD ", "kfa"},
    { L"Kokni", "KKN ", "kex"},
    { L"Komi", "KOM ", "kv"},
    { L"Komi-Permyak", "KOP ", "koi"},
    { L"Komi-Zyrian", "KOZ ", "kpv"},
    { L"Komo", "KMO ", "kmw"},
    { L"Komso", "KMS ", "kxc"},
    { L"Kongo", "KON0", "kg"},
    { L"Konkani", "KOK ", "gom"},
    { L"Koorete", "KRT ", "kqy"},
    { L"Korean Old Hangu", "KOH ", "okm"},
    { L"Korean", "KOR ", "ko"},
    { L"Koryak", "KYK ", "kpy"},
    { L"Kosraean", "KOS ", "kos"},
    { L"Kpelle (Guinea)", "GKP ", "gkp"},
    { L"Kpelle (Liberia)", "XPE ", "xpe"},
    { L"Kpelle", "KPL ", "kpe"},
    { L"Krio", "KRI ", "kri"},
    { L"Krymchak", "JCT ", "jct"},
    { L"Kuanyama", "KUA ", "kj"},
    { L"Kui", "KUI ", "kxu"},
    { L"Kulvi", "KUL ", "kfx"},
    { L"Kumaoni", "KMN ", "kfy"},
    { L"Kumyk", "KUM ", "kum"},
    { L"Kurdish", "KUR ", "ckb"},
    { L"Kurukh", "KUU ", "kru"},
    { L"Kuy", "KUY ", "kdt"},
    { L"K’iche’", "QUC ", "quc"},
    { L"L-Cree", "LCR ", "crm"},
    { L"Ladakhi", "LDK ", "lbj"},
    { L"Ladin", "LAD ", "lld"},
    { L"Ladino", "JUD ", "lad"},
    { L"Lahuli", "LAH ", "bfu"},
    { L"Lak", "LAK ", "lbe"},
    { L"Laki", "LKI ", "lki"},
    { L"Lambani", "LAM ", "lmn"},
    { L"Lampung", "LJP ", "ljp"},
    { L"Lao", "LAO ", "lo"},
    { L"Latin", "LAT ", "la"},
    { L"Latvian", "LVI ", "ltg"},
    { L"Laz", "LAZ ", "lzz"},
    { L"Lezgi", "LEZ ", "lez"},
    { L"Ligurian", "LIJ ", "lij"},
    { L"Limbu", "LMB ", "lif"},
    { L"Limburgish", "LIM ", "li"},
    { L"Lingala", "LIN ", "ln"},
    { L"Lisu", "LIS ", "lis"},
    { L"Lithuanian", "LTH ", "lt"},
    { L"Lojban", "JBO ", "jbo"},
    { L"Loma", "LOM ", "lom"},
    { L"Lombard", "LMO ", "lmo"},
    { L"Lomwe", "LMW ", "ngl"},
    { L"Low Mari", "LMA ", "mhr"},
    { L"Low Saxon", "NDS ", "nds"},
    { L"Lower Sorbian", "LSB ", "dsb"},
    { L"Luba-Katanga", "LUB ", "lu"},
    { L"Luba-Lulua", "LUA ", "lua"},
    { L"Lule Sami", "LSM ", "smj"},
    { L"Luo", "LUO ", "luo"},
    { L"Luri", "LRC ", "bqi"},
    { L"Luxembourgish", "LTZ ", "lb"},
    { L"Luyia", "LUH ", "bxk"},
    { L"Lü", "XBD ", "khb"},
    { L"Macedonian", "MKD ", "mk"},
    { L"Madura", "MAD ", "mad"},
    { L"Magahi", "MAG ", "mag"},
    { L"Maithili", "MTH ", "mai"},
    { L"Majang", "MAJ ", "mpe"},
    { L"Makasar", "MKR ", "mak"},
    { L"Makhuwa", "MAK ", "vmw"},
    { L"Makonde", "KDE ", "kde"},
    { L"Malagasy", "MLG ", "bhr"},
    { L"Malay", "MLY ", "bjn"},
    { L"Malayalam Reformed", "MLR ", "ml"},
    { L"Malayalam", "MAL ", "ml"},
    { L"Male", "MLE ", "mdy"},
    { L"Malinke", "MLN ", "mlq"},
    { L"Maltese", "MTS ", "mt"},
    { L"Mam", "MAM ", "mam"},
    { L"Manchu", "MCH ", "mnc"},
    { L"Mandar", "MDR ", "mdr"},
    { L"Mandinka", "MND ", "mnk"},
    { L"Maninka", "MNK ", "emk"},
    { L"Manipuri", "MNI ", "mni"},
    { L"Mansi", "MAN ", "mns"},
    { L"Manx", "MNX ", "gv"},
    { L"Maori", "MRI ", "mi"},
    { L"Mapudungun", "MAP ", "arn"},
    { L"Marathi", "MAR ", "mr"},
    { L"Marshallese", "MAH ", "mh"},
    { L"Marwari", "MAW ", "dhd"},
    { L"Mayan", "MYN ", "myn"},
    { L"Mazanderani", "MZN ", "mzn"},
    { L"Mbembe Tigon", "NZA ", "nza"},
    { L"Mbo", "MBO ", "mbo"},
    { L"Mbundu", "MBN ", "kmb"},
    { L"Medumba", "BYV ", "byv"},
    { L"Mende", "MDE ", "men"},
    { L"Meru", "MER ", "mer"},
    { L"Mewati", "WTM ", "wtm"},
    { L"Me’en", "MEN ", "mym"},
    { L"Minangkabau", "MIN ", "min"},
    { L"Minjangba", "XJB ", "xjb"},
    { L"Mirandese", "MWL ", "mwl"},
    { L"Mizo", "MIZ ", "lus"},
    { L"Mohawk", "MOH ", "moh"},
    { L"Moksha", "MOK ", "mdf"},
    { L"Moldavian", "MOL ", "mo"},
    { L"Mon", "MON ", "mnw"},
    { L"Mongolian", "MNG ", "drh"},
    { L"Moose Cree", "MCR ", "crm"},
    { L"Morisyen", "MFE ", "mfe"},
    { L"Moroccan", "MOR ", "ary"},
    { L"Mossi", "MOS ", "mos"},
    { L"Mundari", "MUN ", "unr"},
    { L"Muscogee", "MUS ", "mus"},
    { L"N-Cree", "NCR ", "csw"},
    { L"Naga-Assamese", "NAG ", "nag"},
    { L"Nagari", "NGR ", ""},
    { L"Nahuat", "NAH ", "nah"},
    { L"Nanai", "NAN ", "gld"},
    { L"Naskapi", "NAS ", "nsk"},
    { L"Nauruan", "NAU ", "na"},
    { L"Navajo", "NAV ", "nv"},
    { L"Ndau", "NDC ", "ndc"},
    { L"Ndebele", "NDB ", "nd"},
    { L"Ndonga", "NDG ", "ng"},
    { L"Neapolitan", "NAP ", "nap"},
    { L"Nepali", "NEP ", "dty"},
    { L"Newari", "NEW ", "new"},
    { L"Ngbaka", "NGA ", "nga"},
    { L"Nigerian Fulfulde", "FUV ", "fuv"},
    { L"Nimadi", "NOE ", "noe"},
    { L"Nisi", "NIS ", "dap"},
    { L"Niuean", "NIU ", "niu"},
    { L"Nogai", "NOG ", "nog"},
    { L"Norfolk", "PIH ", "pih"},
    { L"North Slavey", "SCS ", "scs"},
    { L"Northern Sami", "NSM ", "se"},
    { L"Northern Tai", "NTA ", "nod"},
    { L"Norway House Cree", "NHC ", "csw"},
    { L"Norwegian Nynorsk (Nynorsk, Norwegian)", "NYN ", ""},
    { L"Norwegian", "NOR ", "nb"},
    { L"Novia", "NOV ", "nov"},
    { L"Nyamwezi", "NYM ", "nym"},
    { L"Nyankole", "NKL ", "nyn"},
    { L"N’Ko", "NKO ", "nqo"},
    { L"Occitan", "OCI ", "oc"},
    { L"Odia (formerly Oriya)", "ORI ", "or"},
    { L"Oji-Cree", "OCR ", "ojs"},
    { L"Ojibway", "OJB ", "ciw"},
    { L"Old Irish", "SGA ", "sga"},
    { L"Oromo", "ORO ", "gax"},
    { L"Ossetian", "OSS ", "os"},
    { L"Palauan", "PAU ", "pau"},
    { L"Palaung", "PLG ", "pce"},
    { L"Palestinian Aramaic", "PAA ", "sam"},
    { L"Pali", "PAL ", "pi"},
    { L"Palpa", "PAP ", "plp"},
    { L"Pampangan", "PAM ", "pam"},
    { L"Pangasinan", "PAG ", "pag"},
    { L"Papiamentu", "PAP0", "pap"},
    { L"Pashto", "PAS ", "pbt"},
    { L"Pattani Malay", "MFA ", "mfa"},
    { L"Pa’o Karen", "BLK ", "blk"},
    { L"Pennsylvania German", "PDC ", "pdc"},
    { L"Persian", "FAR ", "fa"},
    { L"Phake", "PHK ", "phk"},
    { L"Phonetic transcription—Americanist conventions", "APPH", ""},
    { L"Phonetic transcription—IPA conventions", "IPPH", ""},
    { L"Picard", "PCD ", "pcd"},
    { L"Piemontese", "PMS ", "pms"},
    { L"Pocomchi", "POH ", "poh"},
    { L"Pohnpeian", "PON ", "pon"},
    { L"Polish", "PLK ", "pl"},
    { L"Polytonic Greek", "PGR ", ""},
    { L"Portuguese", "PTG ", "pt"},
    { L"Provençal / Old Provença", "PRO ", "pro"},
    { L"Punjabi", "PAN ", "pa"},
    { L"Quechua (Bolivia)", "QUH ", "cqu"},
    { L"Quechua (Ecuador)", "QVI ", "qud"},
    { L"Quechua (Peru)", "QWH ", "qub"},
    { L"Quechua", "QUZ ", "qu"},
    { L"R-Cree", "RCR ", "atj"},
    { L"Rajasthani", "RAJ ", "gda"},
    { L"Rakhine", "ARK ", "ccq"},
    { L"Rarotongan", "RAR ", "rar"},
    { L"Rejang", "REJ ", "rej"},
    { L"Riang", "RIA ", "ria"},
    { L"Ripuarian", "KSH0", "ksh"},
    { L"Ritarungo", "RIT ", "rit"},
    { L"Romanian", "ROM ", "ro"},
    { L"Romansh", "RMS ", "rm"},
    { L"Romany", "ROY ", "rmc"},
    { L"Rotuman", "RTM ", "rtm"},
    { L"Rundi", "RUN ", "rn"},
    { L"Russian Buriat", "RBU ", "bxr"},
    { L"Russian", "RUS ", "ru"},
    { L"Rusyn", "RSY ", "rue"},
    { L"Sadri", "SAD ", "sck"},
    { L"Sakha", "YAK ", "sah"},
    { L"Samoan", "SMO ", "sm"},
    { L"Samogitian", "SGS ", "sgs"},
    { L"San Blas Kuna", "CUK ", "cuk"},
    { L"Sango", "SGO ", "sg"},
    { L"Sanskrit", "SAN ", "sa"},
    { L"Santali", "SAT ", "sat"},
    { L"Saraiki", "SRK ", "skr"},
    { L"Sardinian", "SRD ", "sc"},
    { L"Sasak", "SAS ", "sas"},
    { L"Saterland Frisian", "STQ ", "stq"},
    { L"Sayisi", "SAY ", "chp"},
    { L"Scots", "SCO ", "sco"},
    { L"Scottish Gaelic (Gaelic)", "GAE ", "gd"},
    { L"Sekota", "SEK ", "xan"},
    { L"Selkup", "SEL ", "sel"},
    { L"Sena", "SNA ", "seh"},
    { L"Serbian", "SRB ", "sr"},
    { L"Serer", "SRR ", "srr"},
    { L"Shan", "SHN ", "shn"},
    { L"Shona", "SNA0", "sn"},
    { L"Sibe", "SIB ", "sjo"},
    { L"Sicilian", "SCN ", "scn"},
    { L"Sidamo", "SID ", "sid"},
    { L"Silesian", "SZL ", "szl"},
    { L"Silte Gurage", "SIG ", "stv"},
    { L"Sindhi", "SND ", "sd"},
    { L"Sinhala (Sinhalese)", "SNH ", "si"},
    { L"Skolt Sami", "SKS ", "sms"},
    { L"Slavey", "SLA ", "den"},
    { L"Slovak", "SKY ", "sk"},
    { L"Slovenian", "SLV ", "sl"},
    { L"Sodo Gurage", "SOG ", "gru"},
    { L"Soga", "XOG ", "xog"},
    { L"Somali", "SML ", "so"},
    { L"Songe", "SOP ", "sop"},
    { L"Soninke", "SNK ", "snk"},
    { L"Sotho, Northern", "NSO ", ""},
    { L"Sotho, Southern", "SOT ", ""},
    { L"South Slavey", "SSL ", "xsl"},
    { L"Southern Kiwai", "KJD ", "kjd"},
    { L"Southern Sami", "SSM ", "sma"},
    { L"Spanish", "ESP ", "es"},
    { L"Standard Moroccan Tamazight", "ZGH ", "zgh"},
    { L"Sukuma", "SUK ", "suk"},
    { L"Sundanese", "SUN ", "su"},
    { L"Suri", "SUR ", "suq"},
    { L"Sutu", "SXT ", "ngo"},
    { L"Svan", "SVA ", "sva"},
    { L"Swadaya Aramaic", "SWA ", "aii"},
    { L"Swahili", "SWK ", "sw"},
    { L"Swati", "SWZ ", "ss"},
    { L"Swedish", "SVE ", "sv"},
    { L"Sylheti", "SYL ", "syl"},
    { L"Syriac", "SYR ", "aii"},
    { L"Syriac, Eastern (ISO 15924 'Syrn')", "SYRN", ""},
    { L"Syriac, Estrangela (ISO 15924 'Syre')", "SYRE", ""},
    { L"Syriac, Western (ISO 15924 'Syrj')", "SYRJ", ""},
    { L"S’gaw Karen", "KSW ", "ksw"},
    { L"Tabasaran", "TAB ", "tab"},
    { L"Tachelhit", "SHI ", "shi"},
    { L"Tagalog", "TGL ", "tl"},
    { L"Tahitian", "THT ", "ty"},
    { L"Tajiki", "TAJ ", "tg"},
    { L"Tamashek", "TMH ", "taq"},
    { L"Tamazight", "TZM ", "tzm"},
    { L"Tami", "TAM ", "ta"},
    { L"Tarifit", "RIF ", "rif"},
    { L"Tatar", "TAT ", "tt"},
    { L"Telugu", "TEL ", "te"},
    { L"Temne", "TMN ", "tem"},
    { L"Tetum", "TET ", "tet"},
    { L"TH-Cree", "TCR ", "cwd"},
    { L"Thai", "THA ", "th"},
    { L"Tibetan", "TIB ", "bo"},
    { L"Tigre", "TGR ", "tig"},
    { L"Tigrinya", "TGY ", "ti"},
    { L"Tiv", "TIV ", "tiv"},
    { L"Todo", "TOD ", "xal"},
    { L"Tok Pisin", "TPI ", "tpi"},
    { L"Toma", "TOD0", "tod"},
    { L"Tonga", "TNG ", "toi"},
    { L"Tongan", "TGN ", "to"},
    { L"Torki", "AZB ", "azb"},
    { L"Tshangla", "TSJ ", "tsj"},
    { L"Tsonga", "TSG ", "ts"},
    { L"Tswana", "TNA ", "tn"},
    { L"Tulu", "TUM ", "tum"},
    { L"Tumbuka", "TUL ", "tcy"},
    { L"Tundra Nenets", "TNE ", "enh"},
    { L"Turkish", "TRK ", "tr"},
    { L"Turkmen", "TKM ", "tk"},
    { L"Turoyo Aramaic", "TUA ", "tru"},
    { L"Tuvalu", "TVL ", "tvl"},
    { L"Tuvin", "TUV ", "tyv"},
    { L"Twi", "TWI ", "ak"},
    { L"Tzotzi", "TZO ", "tzo"},
    { L"Tày", "TYZ ", "tyz"},
    { L"Udmurt", "UDM ", "udm"},
    { L"Ukrainian", "UKR ", "uk"},
    { L"Umbundu", "UMB ", "umb"},
    { L"Upper Saxon", "SXU ", "sxu"},
    { L"Upper Sorbian", "USB ", "hsb"},
    { L"Urdu", "URD ", "ur"},
    { L"Uyghur", "UYG ", "ug"},
    { L"Uzbek", "UZB ", "uz"},
    { L"Venda", "VEN ", "ve"},
    { L"Venetian", "VEC ", "vec"},
    { L"Vietnamese", "VIT ", "vi"},
    { L"Vlax Romani", "RMY ", "rmy"},
    { L"Volapük", "VOL ", "vo"},
    { L"Võro", "VRO ", "vro"},
    { L"Wa", "WA ", ""},
    { L"Wagdi", "WAG ", "wbr"},
    { L"Walloon", "WLN ", "wa"},
    { L"Waray-Waray", "WAR ", "war"},
    { L"Wayuu", "GUC ", "guc"},
    { L"Welsh", "WEL ", "cy"},
    { L"West-Cree", "WCR ", "crk"},
    { L"Western Cham", "CJA ", "cja"},
    { L"Western Kayah", "KYU ", "kyu"},
    { L"Western Panjabi", "PNB ", "pnb"},
    { L"Western Pwo Karen", "PWO ", "pwo"},
    { L"Wolof", "WLF ", "wo"},
    { L"Woods Cree", "DCR ", "cwd"},
    { L"Xhosa", "XHS ", "xh"},
    { L"Y-Cree", "YCR ", "cr"},
    { L"Yao", "YAO ", "yao"},
    { L"Yapese", "YAP ", "yap"},
    { L"Yi Classic", "YIC ", ""},
    { L"Yi Modern", "YIM ", "ii"},
    { L"Yiddish", "JII ", "ji"},
    { L"Yoruba", "YBA ", "yo"},
    { L"Zamboanga Chavacano", "CBK ", "cbk"},
    { L"Zande", "ZND ", "zne"},
    { L"Zarma", "DJR ", "dje"},
    { L"Zazaki", "ZZA ", "zza"},
    { L"Zealandic", "ZEA ", "zea"},
    { L"Zhuang", "ZHA ", "za"},
    { L"Zulu", "ZUL ", "zu"},
};
